export const MOCK_RESTAURANTS = [
  {
    id: 1,
    name: 'Royal Spice Biryani',
    description: 'Authentic Hyderabadi Biryani, Kebabs, and Mughlai delicacies crafted with secret aromatic spices.',
    cuisine: 'Biryani, North Indian',
    address: '124 Park Street, Downtown',
    rating: 4.8,
    deliveryTime: 25,
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&q=80',
    active: true,
  },
  {
    id: 2,
    name: 'Pizzeria Bella Ciao',
    description: 'Hand-tossed Neapolitan pizzas baked in authentic wood-fired stone ovens with imported Mozzarella.',
    cuisine: 'Pizza, Italian',
    address: '45 Tech Hub Blvd, Cybercity',
    rating: 4.7,
    deliveryTime: 20,
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&q=80',
    active: true,
  },
  {
    id: 3,
    name: 'The Burger Joint',
    description: 'Juicy smashed Angus beef burgers, crispy golden fries, and artisanal thick milkshakes.',
    cuisine: 'Burger, Fast Food',
    address: '88 Ocean Drive, Marina',
    rating: 4.6,
    deliveryTime: 18,
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80',
    active: true,
  },
  {
    id: 4,
    name: 'Sakura Sushi Bar',
    description: 'Fresh sashimi grade salmon, dragon rolls, steaming ramen bowls, and traditional bento boxes.',
    cuisine: 'Sushi, Japanese',
    address: '12 Green Avenue, West End',
    rating: 4.9,
    deliveryTime: 30,
    imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&q=80',
    active: true,
  },
  {
    id: 5,
    name: 'Sweet Tooth Dessert Bar',
    description: 'Decadent chocolate lava cakes, Belgian waffles, French macarons, and gourmet gelato scoops.',
    cuisine: 'Dessert, Bakery',
    address: '77 Sugar Lane, City Center',
    rating: 4.8,
    deliveryTime: 15,
    imageUrl: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=600&q=80',
    active: true,
  },
  {
    id: 6,
    name: 'Taco Fiesta Express',
    description: 'Mexican street tacos, loaded cheesy nachos, spicy burritos, and freshly whipped churros.',
    cuisine: 'Tacos, Mexican',
    address: '302 Sunset Blvd',
    rating: 4.5,
    deliveryTime: 22,
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80',
    active: true,
  },
];

export const MOCK_MENUS = {
  1: [
    {
      id: 101,
      name: 'Hyderabadi Chicken Dum Biryani',
      description: 'Slow-cooked fragrant basmati rice layered with succulent marinated chicken and authentic whole spices.',
      price: 14.99,
      category: 'Biryani',
      veg: false,
      available: true,
      imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500&q=80',
    },
    {
      id: 102,
      name: 'Special Veg Paneer Biryani',
      description: 'Charcoal grilled cottage cheese cubes cooked with saffron rice, caramelized onions, and fresh mint.',
      price: 12.99,
      category: 'Biryani',
      veg: true,
      available: true,
      imageUrl: 'https://images.unsplash.com/photo-1642821373181-696a54913e93?w=500&q=80',
    },
    {
      id: 103,
      name: 'Murg Tandoori Kebab (Half)',
      description: 'Chicken marinated in spicy yogurt & roasted over clay oven to smoky perfection.',
      price: 9.99,
      category: 'Starters',
      veg: false,
      available: true,
      imageUrl: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=500&q=80',
    },
    {
      id: 104,
      name: 'Butter Naan Basket (3 pcs)',
      description: 'Freshly baked soft tandoori bread brushed with creamy garlic butter.',
      price: 3.49,
      category: 'Breads',
      veg: true,
      available: true,
      imageUrl: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?w=500&q=80',
    },
  ],
  2: [
    {
      id: 201,
      name: 'Margherita Pepperoni Deluxe Pizza',
      description: 'Double layer pepperoni, spicy San Marzano tomato sauce, and molten buffalo mozzarella.',
      price: 16.49,
      category: 'Pizza',
      veg: false,
      available: true,
      imageUrl: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=500&q=80',
    },
    {
      id: 202,
      name: 'Truffle Mushroom & Spinach Pizza',
      description: 'White base pizza topped with wild portobello mushrooms, fresh spinach, and truffle oil drizzle.',
      price: 15.99,
      category: 'Pizza',
      veg: true,
      available: true,
      imageUrl: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=500&q=80',
    },
    {
      id: 203,
      name: 'Cheesy Garlic Bread Sticks',
      description: 'Oven baked bread coated in herb garlic butter and pulled melted mozzarella.',
      price: 5.99,
      category: 'Starters',
      veg: true,
      available: true,
      imageUrl: 'https://images.unsplash.com/photo-1619535860434-ba1d8fa12536?w=500&q=80',
    },
  ],
  3: [
    {
      id: 301,
      name: 'Double Bacon Smash Cheeseburger',
      description: 'Two smashed grass-fed beef patties, double cheddar cheese, crispy bacon, and house burger sauce.',
      price: 11.99,
      category: 'Burger',
      veg: false,
      available: true,
      imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&q=80',
    },
    {
      id: 302,
      name: 'Crispy Black Bean Veggie Burger',
      description: 'Housemade spicy black bean patty, avocado, lettuce, tomato, and chipotle mayo.',
      price: 9.99,
      category: 'Burger',
      veg: true,
      available: true,
      imageUrl: 'https://images.unsplash.com/photo-1525059696034-4967a8e1dca2?w=500&q=80',
    },
    {
      id: 303,
      name: 'Truffle Seasoned Potato Fries',
      description: 'Golden crispy skin-on potato fries tossed with parmesan cheese and truffle oil.',
      price: 4.99,
      category: 'Sides',
      veg: true,
      available: true,
      imageUrl: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=500&q=80',
    },
  ],
  4: [
    {
      id: 401,
      name: 'Salmon Dragon Roll (8 pcs)',
      description: 'Fresh Norwegian salmon, cucumber, avocado, spicy mayo, and tobiko toppings.',
      price: 16.99,
      category: 'Sushi',
      veg: false,
      available: true,
      imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=500&q=80',
    },
    {
      id: 402,
      name: 'Avocado & Cucumber Veg Roll (8 pcs)',
      description: 'Fresh ripe avocado, crunchy cucumber, and toasted sesame seeds wrapped in sushi rice.',
      price: 10.99,
      category: 'Sushi',
      veg: true,
      available: true,
      imageUrl: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=500&q=80',
    },
  ],
  5: [
    {
      id: 501,
      name: 'Triple Chocolate Molten Lava Cake',
      description: 'Warm chocolate cake with a rich oozing chocolate center served with vanilla gelato.',
      price: 7.99,
      category: 'Dessert',
      veg: true,
      available: true,
      imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=500&q=80',
    },
    {
      id: 502,
      name: 'Belgian Waffle with Berry Compote',
      description: 'Crispy golden waffle drizzled with maple syrup, whipped cream, and fresh berries.',
      price: 8.49,
      category: 'Dessert',
      veg: true,
      available: true,
      imageUrl: 'https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=500&q=80',
    },
  ],
  6: [
    {
      id: 601,
      name: 'Spicy Carne Asada Street Tacos (3 pcs)',
      description: 'Marinated grilled flank steak topped with chopped onions, cilantro, and roasted salsa.',
      price: 10.99,
      category: 'Tacos',
      veg: false,
      available: true,
      imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=500&q=80',
    },
  ],
};
